name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: ["main", "master"]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated to v4

      - name: Setup Pages
        uses: actions/configure-pages@v4 # Updated to v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1 # This version is correct

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Updated to v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Updated to v4